export const AVAILABILITY_SLOTS = [
    { id: "WD_MORNING", label: "Weekday Morning" },
    { id: "WD_AFTERNOON", label: "Weekday Afternoon" },
    { id: "WD_EVENING", label: "Weekday Evening" },
    { id: "WE_MORNING", label: "Weekend Morning" },
    { id: "WE_AFTERNOON", label: "Weekend Afternoon" },
    { id: "WE_EVENING", label: "Weekend Evening" },
];

export const TIMEZONES = [
    "UTC-12",
    "UTC-11",
    "UTC-10",
    "UTC-9",
    "UTC-8",
    "UTC-7",
    "UTC-6",
    "UTC-5",
    "UTC-4",
    "UTC-3",
    "UTC-2",
    "UTC-1",
    "UTC+0",
    "UTC+1",
    "UTC+2",
    "UTC+3",
    "UTC+4",
    "UTC+5",
    "UTC+5:30",
    "UTC+6",
    "UTC+7",
    "UTC+8",
    "UTC+9",
    "UTC+10",
    "UTC+11",
    "UTC+12",
    "UTC+13",
    "UTC+14",
];
